### ISSUE TITLE
Import is referencing github.com/brocaar

### ISSUE THREAD

**Issue by Niondir** [TheThingsNetwork/packet-forwarder-bridge#2]
`cmd/lora-gateway-bridge/main.go` is still referencing the original repo `github.com/brocaar/lora-gateway-bridge/` in the imports.

Might make some trouble when using `go get`

**Comment by htdvisser** [comment]
For the time being we're just a fork, so won't change this.

See http://stackoverflow.com/questions/14323872/using-forked-package-import-in-go/29161911#29161911
